import * as actionTypes from "./actionTypes";

enum Unit {
  None = 0,
  Each = 1,
  M2 = 2,
  WxD = 4,
  DxH = 8,
  WxH = 16,
}

const initialState: ItemState = {
  Items: [
    {
      id: "1",
      enabled: true,
      type: "Concrete",
      width: 10,
      height: 5,
      unit: Unit.M2,
      rate: 50,
      matchSize: true,
      group: "Foundation",
      description: "Concrete foundation",
      summary: "Concrete",
      order: 1,
    },
    {
      id: "2",
      enabled: true,
      type: "Brickwork",
      width: 8,
      height: 3,
      unit: Unit.M2,
      rate: 30,
      matchSize: true,
      group: "Walls",
      description: "Brickwork walls",
      summary: "Brickwork",
      order: 2,
    },
    {
      id: "3",
      enabled: true,
      type: "Roofing",
      width: 100,
      height: 80,
      unit: Unit.M2,
      rate: 120,
      matchSize: true,
      group: "Roof",
      description: "Roofing materials",
      summary: "Roofing",
      order: 3,
    },
    {
      id: "4",
      enabled: true,
      type: "Electrical",
      width: 0,
      height: 0,
      unit: Unit.None,
      rate: 80,
      matchSize: false,
      group: "Installations",
      description: "Electrical wiring and installations",
      summary: "Electrical",
      order: 4,
    },
    {
      id: "5",
      enabled: true,
      type: "Plumbing",
      width: 0,
      height: 0,
      unit: Unit.None,
      rate: 70,
      matchSize: false,
      group: "Installations",
      description: "Plumbing installations and fixtures",
      summary: "Plumbing",
      order: 5,
    },
    {
      id: "6",
      enabled: true,
      type: "Flooring",
      width: 50,
      height: 50,
      unit: Unit.M2,
      rate: 60,
      matchSize: true,
      group: "Floors",
      description: "Flooring materials",
      summary: "Flooring",
      order: 6,
    },
    {
      id: "7",
      enabled: true,
      type: "Windows",
      width: 2,
      height: 2,
      unit: Unit.WxH,
      rate: 150,
      matchSize: true,
      group: "Exterior",
      description: "Windows and glass fittings",
      summary: "Windows",
      order: 7,
    },
    {
      id: "8",
      enabled: true,
      type: "Doors",
      width: 1,
      height: 2.5,
      unit: Unit.WxH,
      rate: 120,
      matchSize: true,
      group: "Exterior",
      description: "Doors and entranceways",
      summary: "Doors",
      order: 8,
    },
    {
      id: "9",
      enabled: true,
      type: "Painting",
      width: 0,
      height: 0,
      unit: Unit.None,
      rate: 40,
      matchSize: false,
      group: "Finishes",
      description: "Painting and finishing works",
      summary: "Painting",
      order: 9,
    },
    {
      id: "10",
      enabled: true,
      type: "HVAC",
      width: 0,
      height: 0,
      unit: Unit.None,
      rate: 100,
      matchSize: false,
      group: "Installations",
      description: "Heating, Ventilation, and Air Conditioning",
      summary: "HVAC",
      order: 10,
    },
    {
      id: "11",
      enabled: true,
      type: "Carpentry",
      width: 0,
      height: 0,
      unit: Unit.None,
      rate: 50,
      matchSize: false,
      group: "Finishes",
      description: "Carpentry and woodworks",
      summary: "Carpentry",
      order: 11,
    },
    {
      id: "12",
      enabled: true,
      type: "Tiles",
      width: 20,
      height: 20,
      unit: Unit.M2,
      rate: 80,
      matchSize: true,
      group: "Finishes",
      description: "Tile works and installations",
      summary: "Tiles",
      order: 12,
    },
    {
      id: "13",
      enabled: true,
      type: "Insulation",
      width: 0,
      height: 0,
      unit: Unit.None,
      rate: 30,
      matchSize: false,
      group: "Roof",
      description: "Insulation materials",
      summary: "Insulation",
      order: 13,
    },
    {
      id: "14",
      enabled: true,
      type: "Stairs",
      width: 0,
      height: 0,
      unit: Unit.None,
      rate: 90,
      matchSize: false,
      group: "Interior",
      description: "Staircases and steps",
      summary: "Stairs",
      order: 14,
    },
    {
      id: "15",
      enabled: true,
      type: "Ceiling",
      width: 0,
      height: 0,
      unit: Unit.None,
      rate: 30,
      matchSize: false,
      group: "Interior",
      description: "Ceiling installations",
      summary: "Ceiling",
      order: 15,
    },
    {
      id: "16",
      enabled: true,
      type: "Drywall",
      width: 0,
      height: 0,
      unit: Unit.None,
      rate: 40,
      matchSize: false,
      group: "Walls",
      description: "Drywall partitions and installations",
      summary: "Drywall",
      order: 16,
    },
    {
      id: "17",
      enabled: true,
      type: "Paving",
      width: 50,
      height: 50,
      unit: Unit.M2,
      rate: 60,
      matchSize: true,
      group: "Exterior",
      description: "Paving and driveway works",
      summary: "Paving",
      order: 17,
    },
    {
      id: "18",
      enabled: true,
      type: "Fencing",
      width: 0,
      height: 0,
      unit: Unit.None,
      rate: 70,
      matchSize: false,
      group: "Exterior",
      description: "Fence and boundary installations",
      summary: "Fencing",
      order: 18,
    },
    {
      id: "19",
      enabled: true,
      type: "Landscaping",
      width: 0,
      height: 0,
      unit: Unit.None,
      rate: 50,
      matchSize: false,
      group: "Exterior",
      description: "Landscaping and garden works",
      summary: "Landscaping",
      order: 19,
    },
    {
      id: "20",
      enabled: true,
      type: "Security",
      width: 0,
      height: 0,
      unit: Unit.None,
      rate: 80,
      matchSize: false,
      group: "Installations",
      description: "Security system installations",
      summary: "Security",
      order: 20,
    },
  ],
};

const reducer = (
  state: ItemState = initialState,
  action: ItemAction
): ItemState => {
  switch (action.type) {
    case actionTypes.EDIT_ITEM:
      const updatedItem: IItem = {
        id: action.Item.id,
        enabled: action.Item.enabled,
        type: action.Item.type,
        width: action.Item.width,
        height: action.Item.height,
        unit: action.Item.unit,
        rate: action.Item.rate,
        matchSize: action.Item.matchSize,
        group: action.Item.group,
        description: action.Item.description,
        summary: action.Item.summary,
        order: action.Item.order,
      };

      let newItems: IItem[] = [];
      state.Items.map((item) => {
        if (updatedItem.id === item.id) {
          return newItems.push(updatedItem);
        } else {
          return newItems.push(item);
        }
      });
      localStorage.setItem("items", JSON.stringify(newItems));
      return {
        ...state,
        Items: newItems,
      };
    case actionTypes.REMOVE_ITEM:
      const updatedItems: IItem[] = state.Items.filter(
        (Item) => Item.id !== action.Item.id
      );
      localStorage.setItem("items", JSON.stringify(updatedItems));
      return {
        ...state,
        Items: updatedItems,
      };
    case actionTypes.INIT_ITEM:
      const items = localStorage.getItem("items");
      if (items !== undefined && items !== null) {
        const itemsJson = JSON.parse(items);
        return {
          ...state,
          Items: itemsJson,
        };
      }
  }
  return state;
};

export default reducer;
